openapi: 3.0.0
info:
  title: VicoHome AI Features API
  description: API for VicoHome AI detection and event settings
  version: 1.0.0

servers:
  - url: https://api-us.vicohome.io
    description: Production API server

paths:
  /aiAssist/queryEventObjectSwitch:
    post:
      tags:
        - AI Features
        - Event Detection
      summary: Query AI event detection settings
      description: Queries AI event object detection settings for devices
      operationId: queryEventObjectSwitch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AiEventEntry'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AiEventResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
                
  /aiAssist/updateEventObjectSwitch:
    post:
      tags:
        - AI Features
        - Event Detection
      summary: Update AI event detection settings
      description: Updates AI event detection settings for devices
      operationId: updateEventObjectSwitch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SwitchAiEventEntry'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
                
  /birdLovers/queryBirdAiSetting:
    post:
      tags:
        - AI Features
        - Bird Detection
      summary: Query bird AI settings
      description: Queries the bird detection AI settings for a specific camera device
      operationId: queryBirdAiSetting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BirdAiQueryEntry'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BirdAiResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
                
  /birdLovers/updateBirdAiSetting:
    post:
      tags:
        - AI Features
        - Bird Detection
      summary: Update bird AI settings
      description: Updates bird detection AI settings for a specific camera device
      operationId: updateBirdAiSetting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BirdAiUpdateEntry'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
                
  /device/queryMessageNotification/v1:
    post:
      tags:
        - AI Features
        - Notification Settings
      summary: Query person detection details
      description: Retrieves message notification settings and configuration for a specific device
      operationId: queryMessageNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageNotificationQueryEntry'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageNotificationResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
                
  /device/updateMessageNotification/v1:
    post:
      tags:
        - AI Features
        - Notification Settings
      summary: Update person detection settings
      description: Updates message notification settings for a specific device
      operationId: updateMessageNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageNotificationUpdateEntry'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'

components:
  schemas:
    BaseEntry:
      type: object
      properties:
        app:
          type: object
          properties:
            type:
              type: string
              description: Application type identifier
              example: "android"
            version:
              type: string
              description: Application version
              example: "1.2.3"
          required:
            - type
            - version
        countryNo:
          type: string
          description: User's country code
          example: "US"
        language:
          type: string
          description: User's language preference
          example: "en"
        tenantId:
          type: string
          description: User's tenant ID
          example: "default"
      required:
        - app
        
    BaseResponse:
      type: object
      properties:
        code:
          type: string
          description: Response code
          example: "0"
        msg:
          type: string
          description: Response message
          example: "Success"
      required:
        - code
        
    AiEventEntry:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseEntry'
        - type: object
          properties:
            isAll:
              type: boolean
              description: Whether to query all devices
              example: true
            serialNumbers:
              type: array
              description: Array of device serial numbers to query (used if isAll is false)
              items:
                type: string
                example: "AB1234567"
          required:
            - isAll
            
    AiEventResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              type: array
              description: List of devices with their AI event detection settings
              items:
                type: object
                properties:
                  serialNumber:
                    type: string
                    description: Device serial number
                    example: "AB1234567"
                  deviceName:
                    type: string
                    description: Name of the device
                    example: "Front Door Camera" 
                  list:
                    type: array
                    description: List of event object detection settings
                    items:
                      $ref: '#/components/schemas/EventObjectSetting'
                      
    EventObjectSetting:
      type: object
      properties:
        eventObject:
          type: string
          description: Type of event object (e.g., "person", "vehicle", "pet", "package", "face")
          example: "person"
        checked:
          type: boolean
          description: Whether detection for this object type is enabled
          example: true
      required:
        - eventObject
        - checked
        
    SwitchAiEventEntry:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseEntry'
        - type: object
          properties:
            serialNumber:
              type: string
              description: Device serial number to update
              example: "AB1234567"
            list:
              type: array
              description: List of event objects to update
              items:
                $ref: '#/components/schemas/EventObjectSetting'
          required:
            - serialNumber
            - list
            
    BirdAiQueryEntry:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseEntry'
        - type: object
          properties:
            serialNumber:
              type: string
              description: Device serial number
              example: "AB1234567"
            reason:
              type: integer
              description: Reason for the query
              default: 0
              example: 0
          required:
            - serialNumber
            
    BirdAiResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                aiAnalyzeSwitch:
                  type: boolean
                  description: Whether AI bird analysis is enabled
                  example: true
                aiNotifySwitch:
                  type: boolean
                  description: Whether AI bird notifications are enabled
                  example: true
                  
    BirdAiUpdateEntry:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseEntry'
        - type: object
          properties:
            serialNumber:
              type: string
              description: Device serial number
              example: "AB1234567"
            aiAnalyzeSwitch:
              type: boolean
              description: Whether AI bird analysis is enabled
              example: true
            aiNotifySwitch:
              type: boolean
              description: Whether bird detection notifications are enabled
              example: true
          required:
            - serialNumber
            
    MessageNotificationQueryEntry:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseEntry'
        - type: object
          properties:
            serialNumber:
              type: string
              description: Device serial number
              example: "AB1234567"
            filterByAiAnalyze:
              type: boolean
              description: Whether to filter results by AI analysis capability
              example: true
            userId:
              type: integer
              description: User ID
              example: 12345
          required:
            - serialNumber
            
    NotificationEventType:
      type: object
      properties:
        name:
          type: string
          description: Event type name (e.g., "person", "vehicle", "pet", "package", "other")
          example: "person"
        choice:
          type: boolean
          description: Whether this event type is selected for notification
          example: true
        subEvent:
          type: array
          description: Optional sub-events for this event type
          items:
            type: object
            properties:
              name:
                type: string
                description: Sub-event name
                example: "face_detected"
              choice:
                type: boolean
                description: Whether this sub-event is selected for notification
                example: true
            required:
              - name
              - choice
      required:
        - name
        - choice
            
    MessageNotificationResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                list:
                  type: array
                  description: List of event types with notification settings
                  items:
                    $ref: '#/components/schemas/NotificationEventType'
                    
    MessageNotificationUpdateEntry:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseEntry'
        - type: object
          properties:
            serialNumber:
              type: string
              description: Device serial number
              example: "AB1234567"
            userId:
              type: integer
              description: User ID
              example: 12345
            eventObjectType:
              type: object
              description: Object containing notification settings for different detection types
              properties:
                person:
                  type: array
                  description: Person detection notification types to enable
                  items:
                    type: string
                    example: "face_detected"
                pet:
                  type: array
                  description: Pet detection notification types to enable
                  items:
                    type: string
                    example: "dog_detected"
                vehicle:
                  type: array
                  description: Vehicle detection notification types to enable
                  items:
                    type: string
                    example: "car_detected"
                other:
                  type: array
                  description: Other detection notification types to enable
                  items:
                    type: string
                    example: "motion_detected"
                package:
                  type: array
                  description: Package detection notification types to enable
                  items:
                    type: string
                    example: "package_delivered"
              required:
                - person
          required:
            - serialNumber
            - eventObjectType