# OpenAPI Spec Merging Progress
target: openapi.yml
children:
  - file: device.yml
    state: [complete]
  - file: location.yml
    state: [complete]
  - file: notification.yml
    state: [complete]
  - file: ai.yml
    state: [complete]
  - file: vip.yml
    state: [complete]
  - file: payment.yml
    state: [complete]
  - file: account.yml
    state: [complete]
    
# All OpenAPI specs have been successfully merged into openapi.yml