# OpenAPI Spec Merging Progress
target: openapi.yml
children:
  - file: device.yml
    state: [complete]
  - file: location.yml
    state: [complete]
  - file: notification.yml
    state: [complete]
  - file: ai.yml
    state: [complete]
  - file: vip.yml
    state: [complete]
  - file: payment.yml
    state: [complete]
  - file: account.yml
    state: [complete]
  - file: library.yml
    state: [complete]
  - file: livestreaming.yml
    state: [complete]
  - file: user.yml
    state: [complete]
    
# Merging progress: 10/10 files merged into openapi.yml