openapi: 3.0.0
info:
  title: VicoHome User API
  description: API for VicoHome user-specific operations
  version: 1.0.0

servers:
  - url: https://api-us.vicohome.io
    description: Production API server

paths:
  /api/userTag:
    post:
      tags:
        - User Management
      summary: Get user bucket parameters for A/B testing
      description: |
        Retrieves user-specific bucket parameters (tags) for A/B testing and feature flag 
        functionality. It's implemented through the GrowthBook SDK for managing features 
        and experiments. The response data is used to determine which features or 
        variations a user should see based on their assigned bucket or segment.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseEntry'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BucketResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    BaseEntry:
      type: object
      properties:
        app:
          type: object
          properties:
            apiVersion:
              type: string
              description: API version
              example: "1.0"
            appName:
              type: string
              description: Application name
              example: "VicoHome"
            appType:
              type: string
              description: Application type
              example: "Android"
            bundle:
              type: string
              description: Bundle identifier
              example: "com.vicoo.vicohome"
            countlyId:
              type: string
              description: Analytics ID
            env:
              type: string
              description: Environment
              example: "prod"
            tenantId:
              type: string
              description: Tenant ID
            timeZone:
              type: string
              description: User's timezone
              example: "America/New_York"
            version:
              type: integer
              description: Application version code
              example: 123
            versionName:
              type: string
              description: Application version name
              example: "1.2.3"
        countryNo:
          type: string
          description: Country code
          example: "US"
        language:
          type: string
          description: User's language preference
          example: "en"
        tenantId:
          type: string
          description: User's tenant ID
          
    BucketResponse:
      type: object
      properties:
        result:
          type: integer
          description: Result code (0 for success)
          example: 0
        msg:
          type: string
          description: Message describing the result
          example: "Success"
        data:
          type: object
          description: User tag attributes
          additionalProperties:
            type: object
          example: {
            "feature_flag_doorbell_pro": true,
            "experiment_new_ui": "variant_a",
            "promo_tier": "premium"
          }
      required:
        - result
        - msg
        
    ErrorResponse:
      type: object
      properties:
        result:
          type: integer
          description: Error code
          example: -1
        msg:
          type: string
          description: Error message
          example: "Error retrieving user tags"
      required:
        - result
        - msg