name: Generate and Publish Godoc

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'

      - name: Install godoc2markdown
        run: go install github.com/davecheney/godoc2md@latest

      - name: Generate documentation
        run: |
          mkdir -p docs
          
          # Generate package documentation
          go list -f '{{.ImportPath}}' ./... | while read pkg; do
            echo "Generating docs for $pkg"
            pkg_path=$(echo $pkg | sed 's|github.com/dydx/vico-cli/||')
            mkdir -p docs/$(dirname $pkg_path)
            godoc2md $pkg > docs/$pkg_path.md
          done
          
          # Create index
          cat > docs/index.md <<EOF
          # Vicohome CLI Documentation
          
          This is the API documentation for the Vicohome CLI tool, generated from godoc comments.
          
          ## Packages
          
          $(go list -f '* [{{.ImportPath}}]({{.ImportPath}}.md)' ./... | sed 's|github.com/dydx/vico-cli/||g')
          
          ## Usage
          
          For usage instructions, please see the [README.md](https://github.com/dydx/vico-cli).
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4